# This is a basic workflow to help you get started with Actions

name: Create new posts

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [trigger-new-repo]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: checkout my-plugin-list
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}

      # Runs a set of commands using the runners shell
      - name: Create posts
        run: |
          ./scripts/scripts/get_updated_repo.sh
  call-workflow:
    needs: [build]
    uses: ./.github/workflows/pages.yml
